"""
Django management command to set up Redis cluster for Django-Q.
"""

import os
import subprocess
import time
from pathlib import Path
from django.core.management.base import BaseCommand, CommandError
from django.conf import settings

class Command(BaseCommand):
    help = 'Set up Redis cluster for Django-Q job processing'
    
    def add_arguments(self, parser):
        parser.add_argument(
            '--redis-port',
            type=int,
            default=6379,
            help='Redis port (default: 6379)'
        )
        parser.add_argument(
            '--redis-password',
            type=str,
            help='Redis password for authentication'
        )
        parser.add_argument(
            '--memory-limit',
            type=str,
            default='2gb',
            help='Redis memory limit (default: 2gb)'
        )
        parser.add_argument(
            '--config-only',
            action='store_true',
            help='Only generate configuration files without starting services'
        )
        parser.add_argument(
            '--install-redis',
            action='store_true',
            help='Install Redis server if not present'
        )
        parser.add_argument(
            '--dry-run',
            action='store_true',
            help='Show what would be done without making changes'
        )
    
    def handle(self, *args, **options):
        self.redis_port = options['redis_port']
        self.redis_password = options['redis_password']
        self.memory_limit = options['memory_limit']
        self.config_only = options['config_only']
        self.install_redis = options['install_redis']
        self.dry_run = options['dry_run']
        
        if self.dry_run:
            self.stdout.write(self.style.WARNING("DRY RUN MODE - No changes will be made"))
        
        try:
            # Check if Redis is installed
            if self.install_redis:
                self._install_redis()
            
            # Generate Redis configuration
            self._generate_redis_config()
            
            # Set up Redis service
            if not self.config_only:
                self._setup_redis_service()
            
            # Test Redis connection
            if not self.config_only and not self.dry_run:
                self._test_redis_connection()
            
            # Update Django settings
            self._update_django_settings()
            
            self.stdout.write(
                self.style.SUCCESS("Redis cluster setup completed successfully!")
            )
            
            if not self.config_only:
                self._print_next_steps()
            
        except Exception as e:
            raise CommandError(f"Error setting up Redis cluster: {str(e)}")
    
    def _install_redis(self):
        """Install Redis server if not present."""
        try:
            # Check if Redis is already installed
            result = subprocess.run(['redis-server', '--version'], 
                                  capture_output=True, text=True)
            if result.returncode == 0:
                self.stdout.write("Redis server is already installed")
                return
        except FileNotFoundError:
            pass
        
        if self.dry_run:
            self.stdout.write("Would install Redis server")
            return
        
        self.stdout.write("Installing Redis server...")
        
        # Update package list
        subprocess.run(['sudo', 'apt', 'update'], check=True)
        
        # Install Redis
        subprocess.run(['sudo', 'apt', 'install', '-y', 'redis-server'], check=True)
        
        self.stdout.write("Redis server installed successfully")
    
    def _generate_redis_config(self):
        """Generate Redis configuration file."""
        config_content = f"""# Redis Configuration for RxDoctor Django-Q
# Generated by setup_redis_cluster command

# Network
port {self.redis_port}
bind 127.0.0.1
protected-mode yes
tcp-backlog 511
timeout 300
tcp-keepalive 60

# General
daemonize yes
supervised systemd
pidfile /var/run/redis/redis-server.pid
loglevel notice
logfile /var/log/redis/redis-server.log
databases 16

# Memory Management
maxmemory {self.memory_limit}
maxmemory-policy allkeys-lru
maxmemory-samples 5

# Persistence
save 300 10
save 60 1000
stop-writes-on-bgsave-error yes
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir /var/lib/redis

# AOF
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb

# Security
"""
        
        if self.redis_password:
            config_content += f"requirepass {self.redis_password}\n"
        
        config_content += """
# Disable dangerous commands
rename-command FLUSHDB ""
rename-command FLUSHALL ""
rename-command DEBUG ""

# Client limits
maxclients 10000
client-output-buffer-limit normal 0 0 0
client-output-buffer-limit replica 256mb 64mb 60
client-output-buffer-limit pubsub 32mb 8mb 60

# Django-Q optimizations
list-max-ziplist-size -1
list-compress-depth 1
hash-max-ziplist-entries 1024
hash-max-ziplist-value 128

# Slow log
slowlog-log-slower-than 10000
slowlog-max-len 128

# Latency monitoring
latency-monitor-threshold 100
"""
        
        config_file = Path('/etc/redis/redis.conf')
        
        if self.dry_run:
            self.stdout.write(f"Would write Redis configuration to {config_file}")
            return
        
        # Backup existing config
        if config_file.exists():
            backup_file = config_file.with_suffix('.conf.backup')
            if not backup_file.exists():
                subprocess.run(['sudo', 'cp', str(config_file), str(backup_file)], check=True)
                self.stdout.write(f"Backed up existing config to {backup_file}")
        
        # Write new configuration
        with open('/tmp/redis.conf', 'w') as f:
            f.write(config_content)
        
        subprocess.run(['sudo', 'mv', '/tmp/redis.conf', str(config_file)], check=True)
        subprocess.run(['sudo', 'chown', 'redis:redis', str(config_file)], check=True)
        subprocess.run(['sudo', 'chmod', '640', str(config_file)], check=True)
        
        self.stdout.write(f"Redis configuration written to {config_file}")
    
    def _setup_redis_service(self):
        """Set up Redis as a system service."""
        if self.dry_run:
            self.stdout.write("Would configure and start Redis service")
            return
        
        # Enable Redis service
        subprocess.run(['sudo', 'systemctl', 'enable', 'redis-server'], check=True)
        
        # Restart Redis with new configuration
        subprocess.run(['sudo', 'systemctl', 'restart', 'redis-server'], check=True)
        
        # Wait for Redis to start
        time.sleep(2)
        
        # Check if Redis is running
        result = subprocess.run(['sudo', 'systemctl', 'is-active', 'redis-server'], 
                              capture_output=True, text=True)
        
        if result.stdout.strip() == 'active':
            self.stdout.write("Redis service is running")
        else:
            raise CommandError("Redis service failed to start")
    
    def _test_redis_connection(self):
        """Test Redis connection."""
        try:
            import redis
            
            # Create Redis client
            client = redis.Redis(
                host='localhost',
                port=self.redis_port,
                password=self.redis_password,
                decode_responses=True
            )
            
            # Test connection
            client.ping()
            
            # Test basic operations
            client.set('test_key', 'test_value', ex=10)
            value = client.get('test_key')
            
            if value == 'test_value':
                self.stdout.write("Redis connection test passed")
            else:
                raise CommandError("Redis connection test failed")
            
            # Clean up test key
            client.delete('test_key')
            
        except ImportError:
            self.stdout.write(
                self.style.WARNING("Redis Python client not installed. Install with: pip install redis")
            )
        except Exception as e:
            raise CommandError(f"Redis connection test failed: {str(e)}")
    
    def _update_django_settings(self):
        """Update Django settings for Redis configuration."""
        settings_updates = {
            'REDIS_HOST': 'localhost',
            'REDIS_PORT': str(self.redis_port),
            'REDIS_DB': '0'
        }
        
        if self.redis_password:
            settings_updates['REDIS_PASSWORD'] = self.redis_password
        
        env_file = Path('.env')
        
        if self.dry_run:
            self.stdout.write(f"Would update environment variables in {env_file}")
            for key, value in settings_updates.items():
                self.stdout.write(f"  {key}={value}")
            return
        
        # Read existing .env file
        env_content = ""
        if env_file.exists():
            with open(env_file, 'r') as f:
                env_content = f.read()
        
        # Update or add settings
        for key, value in settings_updates.items():
            if f"{key}=" in env_content:
                # Update existing setting
                lines = env_content.split('\n')
                for i, line in enumerate(lines):
                    if line.startswith(f"{key}="):
                        lines[i] = f"{key}={value}"
                        break
                env_content = '\n'.join(lines)
            else:
                # Add new setting
                env_content += f"\n{key}={value}"
        
        # Write updated .env file
        with open(env_file, 'w') as f:
            f.write(env_content.strip() + '\n')
        
        self.stdout.write(f"Updated environment variables in {env_file}")
    
    def _print_next_steps(self):
        """Print next steps for the user."""
        self.stdout.write("\n" + "="*50)
        self.stdout.write("Next Steps:")
        self.stdout.write("="*50)
        
        self.stdout.write("1. Verify Redis is running:")
        self.stdout.write("   sudo systemctl status redis-server")
        
        self.stdout.write("\n2. Test Django-Q connection:")
        self.stdout.write("   python manage.py manage_django_q status")
        
        self.stdout.write("\n3. Start Django-Q workers:")
        self.stdout.write("   python manage.py qcluster")
        
        self.stdout.write("\n4. Set up Supervisor for production:")
        self.stdout.write("   sudo cp config/supervisor_django_q.conf /etc/supervisor/conf.d/")
        self.stdout.write("   sudo supervisorctl reread")
        self.stdout.write("   sudo supervisorctl update")
        
        self.stdout.write("\n5. Monitor Django-Q workers:")
        self.stdout.write("   python manage.py manage_django_q monitor")
        
        self.stdout.write("\n6. Set up monitoring cron job:")
        self.stdout.write("   */5 * * * * cd /var/www/rxdoctor && python manage.py manage_django_q health --send-alerts")
        
        if self.redis_password:
            self.stdout.write(f"\nRedis Password: {self.redis_password}")
            self.stdout.write("Make sure to update your Django settings with the Redis password.")
        
        self.stdout.write("\n" + "="*50)