# Generated by Django 5.1.3 on 2025-08-18 05:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClinicalRecord",
            fields=[
                ("tenant_id", models.IntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("record_type", models.CharField(max_length=100)),
                ("status", models.CharField(default="active", max_length=50)),
                ("priority", models.CharField(default="normal", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_confidential", models.BooleanField(default=False)),
                ("record_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "clinical_records",
                "ordering": ["-record_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalDocument",
            fields=[
                ("tenant_id", models.IntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("file_type", models.CharField(max_length=50)),
                ("file_size", models.BigIntegerField()),
                ("mime_type", models.CharField(max_length=100)),
                ("is_encrypted", models.BooleanField(default=False)),
                ("is_processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "clinical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="clinical_records.clinicalrecord",
                    ),
                ),
            ],
            options={
                "db_table": "clinical_documents",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ImagingStudy",
            fields=[
                ("tenant_id", models.IntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("study_type", models.CharField(max_length=100)),
                ("modality", models.CharField(max_length=50)),
                ("study_date", models.DateField()),
                ("study_description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imaging_studies",
                        to="clinical_records.clinicalrecord",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Imaging Studies",
                "db_table": "imaging_studies",
            },
        ),
        migrations.CreateModel(
            name="ManualReview",
            fields=[
                ("tenant_id", models.IntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="pending", max_length=50)),
                ("priority", models.CharField(default="normal", max_length=20)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "clinical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_reviews",
                        to="clinical_records.clinicalrecord",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "manual_reviews",
            },
        ),
        migrations.CreateModel(
            name="RecordRelationship",
            fields=[
                ("tenant_id", models.IntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("relationship_type", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_relationships",
                        to="clinical_records.clinicalrecord",
                    ),
                ),
                (
                    "target_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_relationships",
                        to="clinical_records.clinicalrecord",
                    ),
                ),
            ],
            options={
                "db_table": "record_relationships",
            },
        ),
        migrations.CreateModel(
            name="ReviewerProfile",
            fields=[
                ("tenant_id", models.IntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("specialization", models.CharField(max_length=100)),
                ("max_daily_reviews", models.IntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reviewer_profiles",
            },
        ),
        migrations.CreateModel(
            name="ShareToken",
            fields=[
                ("tenant_id", models.IntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=255, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("access_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "clinical_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_tokens",
                        to="clinical_records.clinicalrecord",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "share_tokens",
            },
        ),
    ]
