# Generated by Django 5.1.3 on 2025-10-25 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical_records", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.IntegerField(default=1)),
                (
                    "rxbackend_patient_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="Patient ID from RxBackend",
                        unique=True,
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(help_text="Patient identifier", max_length=50),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=17)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "clinic_id",
                    models.IntegerField(help_text="Reference to RxBackend clinic"),
                ),
                (
                    "clinic_name",
                    models.CharField(
                        blank=True,
                        help_text="Clinic name from RxBackend",
                        max_length=255,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("blood_group", models.CharField(blank=True, max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "patients",
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.RemoveField(
            model_name="clinicaldocument",
            name="file_path",
        ),
        migrations.AddField(
            model_name="clinicaldocument",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="Upload clinical document",
                null=True,
                upload_to="clinical_documents/%Y/%m/%d/",
            ),
        ),
        migrations.AddField(
            model_name="clinicaldocument",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="clinicaldocument",
            name="file_size",
            field=models.BigIntegerField(
                blank=True, help_text="File size in bytes", null=True
            ),
        ),
        migrations.AlterField(
            model_name="clinicaldocument",
            name="file_type",
            field=models.CharField(
                blank=True, help_text="Auto-detected file type", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="clinicaldocument",
            name="mime_type",
            field=models.CharField(blank=True, help_text="MIME type", max_length=100),
        ),
        migrations.AddIndex(
            model_name="clinicaldocument",
            index=models.Index(
                fields=["clinical_record", "-created_at"],
                name="clinical_do_clinica_05fb79_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clinicaldocument",
            index=models.Index(
                fields=["processing_status"], name="clinical_do_process_c4adb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["rxbackend_patient_id"], name="patients_rxbacke_c4e6ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["clinic_id"], name="patients_clinic__862cc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["patient_id"], name="patients_patient_e63b14_idx"
            ),
        ),
        migrations.AddField(
            model_name="clinicalrecord",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clinical_records",
                to="clinical_records.patient",
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalrecord",
            index=models.Index(
                fields=["patient", "-record_date"],
                name="clinical_re_patient_9e721f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalrecord",
            index=models.Index(
                fields=["record_type"], name="clinical_re_record__4fdb9b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinicalrecord",
            index=models.Index(fields=["status"], name="clinical_re_status_826f96_idx"),
        ),
    ]
