# Generated by Django 5.1.3 on 2026-07-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clinical_records", "0002_patient_remove_clinicaldocument_file_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicalrecord",
            name="external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ID from external system (e.g. RxBackend)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clinicalrecord",
            name="is_sealed",
            field=models.BooleanField(default=False, help_text="Sealed by patient"),
        ),
    ]
